// ============================================================
// iPhone Material Composition Data
// Sources: Apple Environmental Reports, USGS Mineral Commodity
// Summaries, iFixit teardowns, academic LCA studies
// ============================================================

export const materials = {
  "stainless-steel": {
    name: "Stainless Steel",
    category: "Structural Metal",
    color: "#b0bec5",
    icon: "⛓",
    pricePerKg: 3.5,
    sources: [
      { country: "China", flag: "🇨🇳", iso: "cn", pct: 54 },
      { country: "India", flag: "🇮🇳", iso: "in", pct: 6 },
      { country: "Japan", flag: "🇯🇵", iso: "jp", pct: 5 },
      { country: "USA", flag: "🇺🇸", iso: "us", pct: 5 },
    ],
    eco: {
      co2PerKg: 6.15,
      waterPerKg: 56,
      landPerKg: 0.8,
      summary:
        "Iron ore mining strips vegetation and topsoil. Smelting is energy-intensive, powered largely by coal in major producing regions.",
    },
  },
  aluminum: {
    name: "Aluminum",
    category: "Structural Metal",
    color: "#90caf9",
    icon: "🔩",
    pricePerKg: 2.5,
    sources: [
      { country: "China", flag: "🇨🇳", iso: "cn", pct: 57 },
      { country: "India", flag: "🇮🇳", iso: "in", pct: 6 },
      { country: "Russia", flag: "🇷🇺", iso: "ru", pct: 6 },
      { country: "Canada", flag: "🇨🇦", iso: "ca", pct: 5 },
    ],
    eco: {
      co2PerKg: 11.5,
      waterPerKg: 1378,
      landPerKg: 2.5,
      summary:
        "Bauxite mining causes deforestation and generates red mud, a toxic alkaline waste. Smelting requires enormous electricity—often from coal plants.",
    },
  },
  titanium: {
    name: "Titanium",
    category: "Structural Metal",
    color: "#b39ddb",
    icon: "🛡",
    pricePerKg: 35,
    sources: [
      { country: "China", flag: "🇨🇳", iso: "cn", pct: 45 },
      { country: "Russia", flag: "🇷🇺", iso: "ru", pct: 13 },
      { country: "Japan", flag: "🇯🇵", iso: "jp", pct: 14 },
      { country: "Kazakhstan", flag: "🇰🇿", iso: "kz", pct: 7 },
    ],
    eco: {
      co2PerKg: 36,
      waterPerKg: 200,
      landPerKg: 1.2,
      summary:
        "Titanium refining (Kroll process) is extremely energy-intensive. Mining ilmenite/rutile sands disrupts coastal ecosystems.",
    },
  },
  glass: {
    name: "Ceramic Shield Glass",
    category: "Display & Enclosure",
    color: "#80deea",
    icon: "🪟",
    pricePerKg: 30,
    sources: [
      { country: "USA", flag: "🇺🇸", iso: "us", pct: 40 },
      { country: "Japan", flag: "🇯🇵", iso: "jp", pct: 25 },
      { country: "South Korea", flag: "🇰🇷", iso: "kr", pct: 15 },
      { country: "China", flag: "🇨🇳", iso: "cn", pct: 10 },
    ],
    eco: {
      co2PerKg: 1.5,
      waterPerKg: 30,
      landPerKg: 0.3,
      summary:
        "Specialty glass production requires high temperatures (1500°C+). Silica sand mining can damage riverbeds and aquatic habitats.",
    },
  },
  lithium: {
    name: "Lithium",
    category: "Battery Material",
    color: "#fff176",
    icon: "⚡",
    pricePerKg: 15,
    sources: [
      { country: "Australia", flag: "🇦🇺", iso: "au", pct: 47 },
      { country: "Chile", flag: "🇨🇱", iso: "cl", pct: 30 },
      { country: "China", flag: "🇨🇳", iso: "cn", pct: 15 },
      { country: "Argentina", flag: "🇦🇷", iso: "ar", pct: 5 },
    ],
    eco: {
      co2PerKg: 15,
      waterPerKg: 2000,
      landPerKg: 3.5,
      summary:
        "Lithium brine evaporation in Chile and Argentina consumes vast quantities of water in some of the driest places on Earth, threatening indigenous communities and flamingo habitats.",
    },
  },
  cobalt: {
    name: "Cobalt",
    category: "Battery Material",
    color: "#5c6bc0",
    icon: "⛏",
    pricePerKg: 30,
    sources: [
      { country: "DRC", flag: "🇨🇩", iso: "cd", pct: 73 },
      { country: "Indonesia", flag: "🇮🇩", iso: "id", pct: 5 },
      { country: "Russia", flag: "🇷🇺", iso: "ru", pct: 4 },
      { country: "Australia", flag: "🇦🇺", iso: "au", pct: 3 },
    ],
    eco: {
      co2PerKg: 8.3,
      waterPerKg: 250,
      landPerKg: 2.0,
      summary:
        "Over 70% of cobalt comes from the DRC, where artisanal mines often involve child labor and dangerous conditions. Toxic dust contaminates nearby communities.",
    },
  },
  nickel: {
    name: "Nickel",
    category: "Battery Material",
    color: "#a5d6a7",
    icon: "🔋",
    pricePerKg: 16,
    sources: [
      { country: "Indonesia", flag: "🇮🇩", iso: "id", pct: 49 },
      { country: "Philippines", flag: "🇵🇭", iso: "ph", pct: 11 },
      { country: "Russia", flag: "🇷🇺", iso: "ru", pct: 7 },
      { country: "New Caledonia", flag: "🇳🇨", iso: "nc", pct: 6 },
    ],
    eco: {
      co2PerKg: 13.4,
      waterPerKg: 380,
      landPerKg: 2.8,
      summary:
        "Laterite nickel mining in Indonesia involves clear-cutting rainforest. Acid leaching produces toxic tailings often dumped into the sea (deep-sea tailings placement).",
    },
  },
  graphite: {
    name: "Graphite",
    category: "Battery Material",
    color: "#616161",
    icon: "✏️",
    pricePerKg: 1.5,
    sources: [
      { country: "China", flag: "🇨🇳", iso: "cn", pct: 65 },
      { country: "Mozambique", flag: "🇲🇿", iso: "mz", pct: 8 },
      { country: "Brazil", flag: "🇧🇷", iso: "br", pct: 7 },
      { country: "Madagascar", flag: "🇲🇬", iso: "mg", pct: 5 },
    ],
    eco: {
      co2PerKg: 1.8,
      waterPerKg: 30,
      landPerKg: 0.5,
      summary:
        "Graphite dust is a serious health hazard. Processing plants in China have contaminated farmland and water supplies in surrounding villages.",
    },
  },
  copper: {
    name: "Copper",
    category: "Electronics",
    color: "#ffab91",
    icon: "🔌",
    pricePerKg: 9,
    sources: [
      { country: "Chile", flag: "🇨🇱", iso: "cl", pct: 24 },
      { country: "Peru", flag: "🇵🇪", iso: "pe", pct: 10 },
      { country: "DRC", flag: "🇨🇩", iso: "cd", pct: 9 },
      { country: "China", flag: "🇨🇳", iso: "cn", pct: 8 },
    ],
    eco: {
      co2PerKg: 4.1,
      waterPerKg: 130,
      landPerKg: 1.5,
      summary:
        "Copper mining generates enormous waste rock and acid mine drainage. The Escondida mine in Chile uses 525 liters of water per second in a desert region.",
    },
  },
  "rare-earths": {
    name: "Rare Earth Elements",
    category: "Electronics",
    color: "#ce93d8",
    icon: "💎",
    pricePerKg: 250,
    sources: [
      { country: "China", flag: "🇨🇳", iso: "cn", pct: 60 },
      { country: "Myanmar", flag: "🇲🇲", iso: "mm", pct: 13 },
      { country: "Australia", flag: "🇦🇺", iso: "au", pct: 7 },
      { country: "USA", flag: "🇺🇸", iso: "us", pct: 4 },
    ],
    eco: {
      co2PerKg: 30,
      waterPerKg: 1500,
      landPerKg: 4.0,
      summary:
        "Rare earth processing produces radioactive thorium and uranium waste. China's Baotou region has a toxic 'lake' of rare earth processing waste visible from space.",
    },
  },
  tungsten: {
    name: "Tungsten",
    category: "Electronics",
    color: "#bcaaa4",
    icon: "🔨",
    pricePerKg: 35,
    sources: [
      { country: "China", flag: "🇨🇳", iso: "cn", pct: 82 },
      { country: "Vietnam", flag: "🇻🇳", iso: "vn", pct: 5 },
      { country: "Russia", flag: "🇷🇺", iso: "ru", pct: 3 },
      { country: "Bolivia", flag: "🇧🇴", iso: "bo", pct: 2 },
    ],
    eco: {
      co2PerKg: 12.5,
      waterPerKg: 200,
      landPerKg: 1.8,
      summary:
        "Tungsten mining in conflict regions has funded armed groups. Processing produces arsenic-laden waste. China controls 82% of production, creating supply chain risk.",
    },
  },
  tantalum: {
    name: "Tantalum",
    category: "Electronics",
    color: "#ef9a9a",
    icon: "🔬",
    pricePerKg: 150,
    sources: [
      { country: "DRC", flag: "🇨🇩", iso: "cd", pct: 33 },
      { country: "Rwanda", flag: "🇷🇼", iso: "rw", pct: 15 },
      { country: "Brazil", flag: "🇧🇷", iso: "br", pct: 13 },
      { country: "Ethiopia", flag: "🇪🇹", iso: "et", pct: 5 },
    ],
    eco: {
      co2PerKg: 70,
      waterPerKg: 900,
      landPerKg: 3.5,
      summary:
        "A 'conflict mineral'—tantalum mining in the DRC has financed armed groups in a civil war that has killed millions. Artisanal mining devastates forests.",
    },
  },
  tin: {
    name: "Tin",
    category: "Electronics",
    color: "#e0e0e0",
    icon: "🫧",
    pricePerKg: 25,
    sources: [
      { country: "China", flag: "🇨🇳", iso: "cn", pct: 31 },
      { country: "Indonesia", flag: "🇮🇩", iso: "id", pct: 17 },
      { country: "Myanmar", flag: "🇲🇲", iso: "mm", pct: 14 },
      { country: "Peru", flag: "🇵🇪", iso: "pe", pct: 5 },
    ],
    eco: {
      co2PerKg: 16,
      waterPerKg: 340,
      landPerKg: 2.2,
      summary:
        "Tin dredging off Indonesia's Bangka Island destroys coral reefs and mangroves. Miners face dangerous conditions; dozens die each year in collapsed mines.",
    },
  },
  gold: {
    name: "Gold",
    category: "Precious Metal",
    color: "#ffd54f",
    icon: "✨",
    pricePerKg: 65000,
    sources: [
      { country: "China", flag: "🇨🇳", iso: "cn", pct: 11 },
      { country: "Australia", flag: "🇦🇺", iso: "au", pct: 10 },
      { country: "Russia", flag: "🇷🇺", iso: "ru", pct: 9 },
      { country: "Canada", flag: "🇨🇦", iso: "ca", pct: 6 },
    ],
    eco: {
      co2PerKg: 20000,
      waterPerKg: 260000,
      landPerKg: 50,
      summary:
        "Gold mining uses cyanide and mercury, which poison waterways. One gold ring generates 20 tons of mine waste. Artisanal gold mining is the largest source of mercury pollution worldwide.",
    },
  },
  silver: {
    name: "Silver",
    category: "Precious Metal",
    color: "#cfd8dc",
    icon: "🪙",
    pricePerKg: 800,
    sources: [
      { country: "Mexico", flag: "🇲🇽", iso: "mx", pct: 24 },
      { country: "Peru", flag: "🇵🇪", iso: "pe", pct: 15 },
      { country: "China", flag: "🇨🇳", iso: "cn", pct: 13 },
      { country: "Poland", flag: "🇵🇱", iso: "pl", pct: 5 },
    ],
    eco: {
      co2PerKg: 200,
      waterPerKg: 1500,
      landPerKg: 5.0,
      summary:
        "Silver is mostly a byproduct of lead/zinc mining, which generates acid mine drainage and heavy metal contamination of soils and waterways.",
    },
  },
  silicon: {
    name: "Silicon",
    category: "Semiconductors",
    color: "#4dd0e1",
    icon: "💻",
    pricePerKg: 10,
    sources: [
      { country: "China", flag: "🇨🇳", iso: "cn", pct: 67 },
      { country: "Russia", flag: "🇷🇺", iso: "ru", pct: 5 },
      { country: "Brazil", flag: "🇧🇷", iso: "br", pct: 5 },
      { country: "Norway", flag: "🇳🇴", iso: "no", pct: 4 },
    ],
    eco: {
      co2PerKg: 12,
      waterPerKg: 1500,
      landPerKg: 1.0,
      summary:
        "Producing semiconductor-grade silicon requires extreme purification. Quartz mining scars landscapes; refining uses hazardous chemicals like trichlorosilane.",
    },
  },
  plastics: {
    name: "Plastics",
    category: "Polymers",
    color: "#fff9c4",
    icon: "🧫",
    pricePerKg: 2,
    sources: [
      { country: "China", flag: "🇨🇳", iso: "cn", pct: 32 },
      { country: "USA", flag: "🇺🇸", iso: "us", pct: 12 },
      { country: "Saudi Arabia", flag: "🇸🇦", iso: "sa", pct: 8 },
      { country: "South Korea", flag: "🇰🇷", iso: "kr", pct: 6 },
    ],
    eco: {
      co2PerKg: 3.5,
      waterPerKg: 185,
      landPerKg: 0.4,
      summary:
        "Derived from petroleum. Plastics persist for centuries in the environment. Microplastics have been found in human blood, lungs, and placentas.",
    },
  },
};

// ============================================================
// Material composition per phone model (grams)
// Based on Apple Environmental Reports, iFixit teardowns,
// and published lifecycle assessment studies
// ============================================================

export const phones = [
  {
    id: "iphone-x",
    name: "iPhone X",
    year: 2017,
    weight: 174,
    frame: "Stainless Steel",
    display: '5.8" Super Retina OLED',
    chip: "A11 Bionic",
    batteryWh: 10.35,
    retailPrice: 999,
    carbonFootprint: 79,
    changes: [
      { text: "First iPhone with OLED display and Face ID", direction: "neutral" },
      { text: "Stainless steel frame replaced aluminum on flagship", direction: "neutral" },
    ],
    materials: [
      { id: "stainless-steel", grams: 52 },
      { id: "glass", grams: 33 },
      { id: "lithium", grams: 1.0 },
      { id: "cobalt", grams: 6.0 },
      { id: "nickel", grams: 3.5 },
      { id: "graphite", grams: 11 },
      { id: "copper", grams: 15 },
      { id: "rare-earths", grams: 0.9 },
      { id: "tungsten", grams: 4.0 },
      { id: "tantalum", grams: 0.015 },
      { id: "tin", grams: 1.8 },
      { id: "gold", grams: 0.034 },
      { id: "silver", grams: 0.34 },
      { id: "silicon", grams: 3.0 },
      { id: "plastics", grams: 14 },
    ],
  },
  {
    id: "iphone-xr",
    name: "iPhone XR",
    year: 2018,
    weight: 194,
    frame: "Aluminum",
    display: '6.1" Liquid Retina LCD',
    chip: "A12 Bionic",
    batteryWh: 11.16,
    retailPrice: 749,
    carbonFootprint: 62,
    changes: [
      { text: "Aluminum frame reduces titanium/steel demand", direction: "improved" },
      { text: "LCD display uses less indium than OLED", direction: "improved" },
      { text: "Heavier battery increases cobalt content", direction: "neutral" },
    ],
    materials: [
      { id: "aluminum", grams: 28 },
      { id: "stainless-steel", grams: 18 },
      { id: "glass", grams: 38 },
      { id: "lithium", grams: 1.1 },
      { id: "cobalt", grams: 6.5 },
      { id: "nickel", grams: 3.8 },
      { id: "graphite", grams: 12 },
      { id: "copper", grams: 16 },
      { id: "rare-earths", grams: 0.9 },
      { id: "tungsten", grams: 4.2 },
      { id: "tantalum", grams: 0.015 },
      { id: "tin", grams: 1.9 },
      { id: "gold", grams: 0.034 },
      { id: "silver", grams: 0.34 },
      { id: "silicon", grams: 3.0 },
      { id: "plastics", grams: 18 },
    ],
  },
  {
    id: "iphone-xs",
    name: "iPhone XS",
    year: 2018,
    weight: 177,
    frame: "Stainless Steel",
    display: '5.8" Super Retina OLED',
    chip: "A12 Bionic",
    batteryWh: 10.13,
    retailPrice: 999,
    carbonFootprint: 70,
    changes: [
      { text: "Improved water resistance (IP68)", direction: "neutral" },
      { text: "A12 chip is more energy-efficient than A11", direction: "improved" },
    ],
    materials: [
      { id: "stainless-steel", grams: 53 },
      { id: "glass", grams: 34 },
      { id: "lithium", grams: 1.0 },
      { id: "cobalt", grams: 5.8 },
      { id: "nickel", grams: 3.4 },
      { id: "graphite", grams: 10.5 },
      { id: "copper", grams: 15 },
      { id: "rare-earths", grams: 0.9 },
      { id: "tungsten", grams: 4.0 },
      { id: "tantalum", grams: 0.015 },
      { id: "tin", grams: 1.8 },
      { id: "gold", grams: 0.034 },
      { id: "silver", grams: 0.34 },
      { id: "silicon", grams: 3.0 },
      { id: "plastics", grams: 13 },
    ],
  },
  {
    id: "iphone-11",
    name: "iPhone 11",
    year: 2019,
    weight: 194,
    frame: "Aluminum",
    display: '6.1" Liquid Retina LCD',
    chip: "A13 Bionic",
    batteryWh: 11.91,
    retailPrice: 699,
    carbonFootprint: 72,
    changes: [
      { text: "Larger battery capacity (+7%) increases mineral demand", direction: "neutral" },
      { text: "100% recycled rare earths in Taptic Engine", direction: "improved" },
    ],
    materials: [
      { id: "aluminum", grams: 27 },
      { id: "stainless-steel", grams: 18 },
      { id: "glass", grams: 40 },
      { id: "lithium", grams: 1.2 },
      { id: "cobalt", grams: 6.8 },
      { id: "nickel", grams: 4.0 },
      { id: "graphite", grams: 13 },
      { id: "copper", grams: 16 },
      { id: "rare-earths", grams: 1.0 },
      { id: "tungsten", grams: 4.5 },
      { id: "tantalum", grams: 0.015 },
      { id: "tin", grams: 2.0 },
      { id: "gold", grams: 0.034 },
      { id: "silver", grams: 0.34 },
      { id: "silicon", grams: 3.0 },
      { id: "plastics", grams: 17 },
    ],
  },
  {
    id: "iphone-11-pro",
    name: "iPhone 11 Pro",
    year: 2019,
    weight: 188,
    frame: "Stainless Steel",
    display: '5.8" Super Retina XDR OLED',
    chip: "A13 Bionic",
    batteryWh: 15.04,
    retailPrice: 999,
    carbonFootprint: 80,
    changes: [
      { text: "Significantly larger battery (15 Wh) increases cobalt content", direction: "neutral" },
      { text: "100% recycled rare earths in Taptic Engine", direction: "improved" },
      { text: "First 'Pro' model with triple camera system", direction: "neutral" },
    ],
    materials: [
      { id: "stainless-steel", grams: 54 },
      { id: "glass", grams: 36 },
      { id: "lithium", grams: 1.3 },
      { id: "cobalt", grams: 7.2 },
      { id: "nickel", grams: 4.2 },
      { id: "graphite", grams: 13 },
      { id: "copper", grams: 16 },
      { id: "rare-earths", grams: 1.0 },
      { id: "tungsten", grams: 4.5 },
      { id: "tantalum", grams: 0.016 },
      { id: "tin", grams: 2.0 },
      { id: "gold", grams: 0.036 },
      { id: "silver", grams: 0.36 },
      { id: "silicon", grams: 3.0 },
      { id: "plastics", grams: 12 },
    ],
  },
  {
    id: "iphone-12",
    name: "iPhone 12",
    year: 2020,
    weight: 164,
    frame: "Aluminum",
    display: '6.1" Super Retina XDR OLED',
    chip: "A14 Bionic",
    batteryWh: 10.78,
    retailPrice: 799,
    carbonFootprint: 70,
    changes: [
      { text: "First 5G iPhone — new rare earth magnets for MagSafe", direction: "neutral" },
      { text: "Ceramic Shield glass introduced (nano-ceramic crystals)", direction: "neutral" },
      { text: "Smaller & lighter design reduces overall material use", direction: "improved" },
    ],
    materials: [
      { id: "aluminum", grams: 24 },
      { id: "stainless-steel", grams: 14 },
      { id: "glass", grams: 34 },
      { id: "lithium", grams: 1.0 },
      { id: "cobalt", grams: 5.5 },
      { id: "nickel", grams: 3.6 },
      { id: "graphite", grams: 11 },
      { id: "copper", grams: 14 },
      { id: "rare-earths", grams: 1.1 },
      { id: "tungsten", grams: 4.0 },
      { id: "tantalum", grams: 0.015 },
      { id: "tin", grams: 1.8 },
      { id: "gold", grams: 0.034 },
      { id: "silver", grams: 0.34 },
      { id: "silicon", grams: 3.0 },
      { id: "plastics", grams: 12 },
    ],
  },
  {
    id: "iphone-12-pro",
    name: "iPhone 12 Pro",
    year: 2020,
    weight: 189,
    frame: "Stainless Steel",
    display: '6.1" Super Retina XDR OLED',
    chip: "A14 Bionic",
    batteryWh: 10.78,
    retailPrice: 999,
    carbonFootprint: 82,
    changes: [
      { text: "LiDAR scanner adds new sensor components", direction: "neutral" },
      { text: "5G modem increases rare earth and copper demand", direction: "neutral" },
      { text: "98% recycled rare earths in all magnets", direction: "improved" },
    ],
    materials: [
      { id: "stainless-steel", grams: 56 },
      { id: "glass", grams: 36 },
      { id: "lithium", grams: 1.0 },
      { id: "cobalt", grams: 5.5 },
      { id: "nickel", grams: 3.6 },
      { id: "graphite", grams: 11 },
      { id: "copper", grams: 16 },
      { id: "rare-earths", grams: 1.1 },
      { id: "tungsten", grams: 5.0 },
      { id: "tantalum", grams: 0.016 },
      { id: "tin", grams: 1.9 },
      { id: "gold", grams: 0.036 },
      { id: "silver", grams: 0.36 },
      { id: "silicon", grams: 3.0 },
      { id: "plastics", grams: 11 },
    ],
  },
  {
    id: "iphone-13",
    name: "iPhone 13",
    year: 2021,
    weight: 174,
    frame: "Aluminum",
    display: '6.1" Super Retina XDR OLED',
    chip: "A15 Bionic",
    batteryWh: 12.41,
    retailPrice: 799,
    carbonFootprint: 64,
    changes: [
      { text: "Cobalt reduced ~15% vs iPhone 12 through chemistry changes", direction: "improved" },
      { text: "Antenna lines use recycled plastic", direction: "improved" },
      { text: "Carbon footprint dropped from 70 to 64 kg CO2", direction: "improved" },
    ],
    materials: [
      { id: "aluminum", grams: 25 },
      { id: "stainless-steel", grams: 15 },
      { id: "glass", grams: 35 },
      { id: "lithium", grams: 1.2 },
      { id: "cobalt", grams: 5.2 },
      { id: "nickel", grams: 4.3 },
      { id: "graphite", grams: 13 },
      { id: "copper", grams: 15 },
      { id: "rare-earths", grams: 1.2 },
      { id: "tungsten", grams: 4.2 },
      { id: "tantalum", grams: 0.015 },
      { id: "tin", grams: 1.9 },
      { id: "gold", grams: 0.034 },
      { id: "silver", grams: 0.34 },
      { id: "silicon", grams: 3.0 },
      { id: "plastics", grams: 13 },
    ],
  },
  {
    id: "iphone-13-pro",
    name: "iPhone 13 Pro",
    year: 2021,
    weight: 204,
    frame: "Stainless Steel",
    display: '6.1" ProMotion Super Retina XDR OLED',
    chip: "A15 Bionic",
    batteryWh: 11.97,
    retailPrice: 999,
    carbonFootprint: 69,
    changes: [
      { text: "ProMotion 120Hz display — LTPO technology more efficient", direction: "improved" },
      { text: "100% recycled tin in solder of main logic board", direction: "improved" },
      { text: "Heaviest iPhone at 204g increases steel content", direction: "neutral" },
    ],
    materials: [
      { id: "stainless-steel", grams: 60 },
      { id: "glass", grams: 38 },
      { id: "lithium", grams: 1.1 },
      { id: "cobalt", grams: 5.4 },
      { id: "nickel", grams: 4.0 },
      { id: "graphite", grams: 12 },
      { id: "copper", grams: 17 },
      { id: "rare-earths", grams: 1.2 },
      { id: "tungsten", grams: 5.2 },
      { id: "tantalum", grams: 0.016 },
      { id: "tin", grams: 2.0 },
      { id: "gold", grams: 0.036 },
      { id: "silver", grams: 0.36 },
      { id: "silicon", grams: 3.5 },
      { id: "plastics", grams: 12 },
    ],
  },
  {
    id: "iphone-14",
    name: "iPhone 14",
    year: 2022,
    weight: 172,
    frame: "Aluminum",
    display: '6.1" Super Retina XDR OLED',
    chip: "A15 Bionic",
    batteryWh: 12.68,
    retailPrice: 799,
    carbonFootprint: 61,
    changes: [
      { text: "Removable back glass improves repairability", direction: "improved" },
      { text: "Cobalt reduced further (-13% vs iPhone 13)", direction: "improved" },
      { text: "Satellite SOS connectivity (new antenna components)", direction: "neutral" },
    ],
    materials: [
      { id: "aluminum", grams: 24 },
      { id: "stainless-steel", grams: 14 },
      { id: "glass", grams: 34 },
      { id: "lithium", grams: 1.2 },
      { id: "cobalt", grams: 4.8 },
      { id: "nickel", grams: 4.5 },
      { id: "graphite", grams: 13 },
      { id: "copper", grams: 15 },
      { id: "rare-earths", grams: 1.2 },
      { id: "tungsten", grams: 4.2 },
      { id: "tantalum", grams: 0.015 },
      { id: "tin", grams: 1.9 },
      { id: "gold", grams: 0.034 },
      { id: "silver", grams: 0.34 },
      { id: "silicon", grams: 3.0 },
      { id: "plastics", grams: 13 },
    ],
  },
  {
    id: "iphone-14-pro",
    name: "iPhone 14 Pro",
    year: 2022,
    weight: 206,
    frame: "Stainless Steel",
    display: '6.1" ProMotion Super Retina XDR OLED',
    chip: "A16 Bionic",
    batteryWh: 12.38,
    retailPrice: 999,
    carbonFootprint: 65,
    changes: [
      { text: "Dynamic Island replaces notch — reduces display waste", direction: "improved" },
      { text: "A16 chip uses 2nd-gen 5nm (more efficient)", direction: "improved" },
      { text: "100% recycled gold in plating of multiple PCBs", direction: "improved" },
    ],
    materials: [
      { id: "stainless-steel", grams: 62 },
      { id: "glass", grams: 38 },
      { id: "lithium", grams: 1.2 },
      { id: "cobalt", grams: 4.9 },
      { id: "nickel", grams: 4.3 },
      { id: "graphite", grams: 12.5 },
      { id: "copper", grams: 17 },
      { id: "rare-earths", grams: 1.3 },
      { id: "tungsten", grams: 5.5 },
      { id: "tantalum", grams: 0.016 },
      { id: "tin", grams: 2.0 },
      { id: "gold", grams: 0.036 },
      { id: "silver", grams: 0.36 },
      { id: "silicon", grams: 3.5 },
      { id: "plastics", grams: 11 },
    ],
  },
  {
    id: "iphone-15",
    name: "iPhone 15",
    year: 2023,
    weight: 171,
    frame: "Aluminum",
    display: '6.1" Super Retina XDR OLED',
    chip: "A16 Bionic",
    batteryWh: 12.98,
    retailPrice: 799,
    carbonFootprint: 56,
    changes: [
      { text: "USB-C replaces Lightning — universal standard reduces e-waste", direction: "improved" },
      { text: "75% recycled aluminum in enclosure", direction: "improved" },
      { text: "100% recycled cobalt in battery", direction: "improved" },
    ],
    materials: [
      { id: "aluminum", grams: 25 },
      { id: "stainless-steel", grams: 12 },
      { id: "glass", grams: 34 },
      { id: "lithium", grams: 1.2 },
      { id: "cobalt", grams: 4.2 },
      { id: "nickel", grams: 5.0 },
      { id: "graphite", grams: 13.5 },
      { id: "copper", grams: 15 },
      { id: "rare-earths", grams: 1.3 },
      { id: "tungsten", grams: 4.0 },
      { id: "tantalum", grams: 0.015 },
      { id: "tin", grams: 1.9 },
      { id: "gold", grams: 0.034 },
      { id: "silver", grams: 0.34 },
      { id: "silicon", grams: 3.0 },
      { id: "plastics", grams: 12 },
    ],
  },
  {
    id: "iphone-15-pro",
    name: "iPhone 15 Pro",
    year: 2023,
    weight: 187,
    frame: "Titanium",
    display: '6.1" ProMotion Super Retina XDR OLED',
    chip: "A17 Pro",
    batteryWh: 12.74,
    retailPrice: 999,
    carbonFootprint: 56,
    changes: [
      { text: "Titanium frame replaces stainless steel — 19g lighter", direction: "improved" },
      { text: "100% recycled cobalt in battery", direction: "improved" },
      { text: "Action button replaces mute switch (fewer moving parts)", direction: "improved" },
      { text: "First 3nm chip in a phone (A17 Pro)", direction: "improved" },
    ],
    materials: [
      { id: "titanium", grams: 22 },
      { id: "aluminum", grams: 12 },
      { id: "stainless-steel", grams: 10 },
      { id: "glass", grams: 36 },
      { id: "lithium", grams: 1.2 },
      { id: "cobalt", grams: 4.0 },
      { id: "nickel", grams: 5.2 },
      { id: "graphite", grams: 13 },
      { id: "copper", grams: 17 },
      { id: "rare-earths", grams: 1.4 },
      { id: "tungsten", grams: 5.0 },
      { id: "tantalum", grams: 0.016 },
      { id: "tin", grams: 2.0 },
      { id: "gold", grams: 0.036 },
      { id: "silver", grams: 0.36 },
      { id: "silicon", grams: 3.5 },
      { id: "plastics", grams: 10 },
    ],
  },
  {
    id: "iphone-16",
    name: "iPhone 16",
    year: 2024,
    weight: 170,
    frame: "Aluminum",
    display: '6.1" Super Retina XDR OLED',
    chip: "A18",
    batteryWh: 13.56,
    retailPrice: 799,
    carbonFootprint: 56,
    changes: [
      { text: "85%+ recycled metals across main logic board", direction: "improved" },
      { text: "100% recycled cobalt in battery (continued)", direction: "improved" },
      { text: "Camera Control button adds new haptic component", direction: "neutral" },
    ],
    materials: [
      { id: "aluminum", grams: 25 },
      { id: "stainless-steel", grams: 11 },
      { id: "glass", grams: 34 },
      { id: "lithium", grams: 1.3 },
      { id: "cobalt", grams: 3.8 },
      { id: "nickel", grams: 5.5 },
      { id: "graphite", grams: 14 },
      { id: "copper", grams: 15 },
      { id: "rare-earths", grams: 1.4 },
      { id: "tungsten", grams: 4.0 },
      { id: "tantalum", grams: 0.015 },
      { id: "tin", grams: 1.9 },
      { id: "gold", grams: 0.034 },
      { id: "silver", grams: 0.34 },
      { id: "silicon", grams: 3.0 },
      { id: "plastics", grams: 11 },
    ],
  },
  {
    id: "iphone-16-pro",
    name: "iPhone 16 Pro",
    year: 2024,
    weight: 199,
    frame: "Titanium",
    display: '6.3" ProMotion Super Retina XDR OLED',
    chip: "A18 Pro",
    batteryWh: 14.06,
    retailPrice: 999,
    carbonFootprint: 56,
    changes: [
      { text: "100% recycled gold in plating of all printed circuit boards", direction: "improved" },
      { text: "100% recycled cobalt, 100% recycled lithium in battery", direction: "improved" },
      { text: "Larger 6.3\" display increases glass content", direction: "neutral" },
    ],
    materials: [
      { id: "titanium", grams: 24 },
      { id: "aluminum", grams: 13 },
      { id: "stainless-steel", grams: 10 },
      { id: "glass", grams: 38 },
      { id: "lithium", grams: 1.3 },
      { id: "cobalt", grams: 3.6 },
      { id: "nickel", grams: 5.8 },
      { id: "graphite", grams: 14 },
      { id: "copper", grams: 18 },
      { id: "rare-earths", grams: 1.5 },
      { id: "tungsten", grams: 5.0 },
      { id: "tantalum", grams: 0.016 },
      { id: "tin", grams: 2.0 },
      { id: "gold", grams: 0.036 },
      { id: "silver", grams: 0.36 },
      { id: "silicon", grams: 3.5 },
      { id: "plastics", grams: 10 },
    ],
  },
  {
    id: "iphone-17",
    name: "iPhone 17",
    year: 2025,
    weight: 172,
    frame: "Aluminum",
    display: '6.1" ProMotion Super Retina XDR OLED',
    chip: "A19",
    batteryWh: 14.5,
    retailPrice: 799,
    carbonFootprint: 52,
    changes: [
      { text: "ProMotion 120Hz comes to standard model for first time", direction: "improved" },
      { text: "Further carbon footprint reduction to ~52 kg CO2", direction: "improved" },
      { text: "Over 90% recycled metals across logic board", direction: "improved" },
      { text: "Cobalt per phone at all-time low for standard model", direction: "improved" },
    ],
    materials: [
      { id: "aluminum", grams: 24 },
      { id: "stainless-steel", grams: 10 },
      { id: "glass", grams: 34 },
      { id: "lithium", grams: 1.3 },
      { id: "cobalt", grams: 3.4 },
      { id: "nickel", grams: 5.8 },
      { id: "graphite", grams: 14.5 },
      { id: "copper", grams: 15 },
      { id: "rare-earths", grams: 1.5 },
      { id: "tungsten", grams: 4.0 },
      { id: "tantalum", grams: 0.015 },
      { id: "tin", grams: 1.9 },
      { id: "gold", grams: 0.034 },
      { id: "silver", grams: 0.34 },
      { id: "silicon", grams: 3.0 },
      { id: "plastics", grams: 11 },
    ],
  },
  {
    id: "iphone-17-pro",
    name: "iPhone 17 Pro",
    year: 2025,
    weight: 194,
    frame: "Titanium",
    display: '6.3" ProMotion Super Retina XDR OLED',
    chip: "A19 Pro",
    batteryWh: 15.0,
    retailPrice: 1099,
    carbonFootprint: 54,
    changes: [
      { text: "Titanium-aluminum composite frame reduces weight vs pure titanium", direction: "improved" },
      { text: "100% recycled cobalt, lithium, gold, copper, and tin", direction: "improved" },
      { text: "2nm A19 Pro chip — most energy-efficient yet", direction: "improved" },
      { text: "Higher recycled content than any previous iPhone", direction: "improved" },
    ],
    materials: [
      { id: "titanium", grams: 20 },
      { id: "aluminum", grams: 16 },
      { id: "stainless-steel", grams: 8 },
      { id: "glass", grams: 38 },
      { id: "lithium", grams: 1.4 },
      { id: "cobalt", grams: 3.2 },
      { id: "nickel", grams: 6.0 },
      { id: "graphite", grams: 15 },
      { id: "copper", grams: 18 },
      { id: "rare-earths", grams: 1.5 },
      { id: "tungsten", grams: 5.0 },
      { id: "tantalum", grams: 0.016 },
      { id: "tin", grams: 2.0 },
      { id: "gold", grams: 0.036 },
      { id: "silver", grams: 0.36 },
      { id: "silicon", grams: 3.5 },
      { id: "plastics", grams: 9 },
    ],
  },
];

// ============================================================
// Insight cards — thought-provoking facts for the UI
// ============================================================
export const insights = [
  {
    title: "The Gold in Your Pocket",
    text: "Your phone contains about 0.034 g of gold — worth ~$2. But mining that gold required moving roughly 30 kg of rock and using cyanide leaching that can poison waterways for decades.",
  },
  {
    title: "Conflict Minerals",
    text: "Tantalum, tin, tungsten, and gold (the '3TG') are designated conflict minerals. Mining them in the DRC has funded armed groups in a conflict that has displaced millions.",
  },
  {
    title: "Water Cost of Lithium",
    text: "Extracting lithium from South American salt flats consumes ~2 million liters of water per ton — in some of the driest places on Earth, competing with indigenous farming communities.",
  },
  {
    title: "China's Rare Earth Dominance",
    text: "China controls ~60% of rare earth mining and ~90% of processing. A single supply disruption could halt global electronics production. Your phone's haptic engine and speakers depend on these elements.",
  },
  {
    title: "Raw Materials ≠ Retail Price",
    text: "The raw materials in your iPhone cost roughly $1–3. The other $797–997 covers R&D, manufacturing, software, marketing, logistics, and profit — illuminating the vast gap between resource cost and consumer price.",
  },
  {
    title: "30+ Countries, One Device",
    text: "The minerals in a single iPhone are sourced from over 30 countries across 6 continents, travel thousands of miles through complex supply chains, and pass through dozens of refineries before assembly.",
  },
];
